### ISSUE TITLE
Remover os valores nos dados de radiância

### ISSUE THREAD

**Issue by LivianyPViana** [GAD-DIMNT-CPTEC/readDiag#13]
Nos dados de radiância há valores exorbitantes que interfere nos cálculos do impacto, valores maiores que -99999 (-999999986991104.0). Portanto, tem-se a necessidade de retirá-los para melhor obter os resultados esperados.

**Comment by joaogerd** [comment]
Corrigido o problema.
o valor descrito nesta issue é definido como undef no código python, que pode ser obtido pela variável _undef.
No entanto, esta valor deveria ser substituído pelo valor numpy.nan(). O que ocorre no problema em questão é que os valores são substituídos somente quando são lidos os dois arquivos pelo read_diag, ou seja, os arquivos de diagnósticos relativos ao first guess e análise e então obtém-se os valores de impacto. Do contrário o valor _undef não é substituído por NaN.

Outro problema é que os valores de _undef são somente substituídos nas colunas "oer", "imp", "dfs" e caso ocorram em outra coluna o mesmo não é substituído.

A correção do bug, realizada no commit 9a5285c, corrige este problema e permite que o valor _undef seja substituído pelo valor NaN em qualquer ocorrência dentro do DataFrame dos dados.
