### ISSUE TITLE
Aprimoramento das funções de plotagem do readDiag

### ISSUE THREAD

**Issue by cfbastarz** [GAD-DIMNT-CPTEC/readDiag#20]
Nesta issue será criado um novo branch para acomodar os desenvolvimentos realizados pelo @edervendrasco sobre o aprimoramento das funções de plotagem do readDiag.

## Procedimentos para a abertura do branch

O branch poderá ser aberto utilizando a própria interface do GitHub. Considerando que uma cópia local do readDiag já existe (i.e., a cópia em que se está trabalhando), basta clicar no link "Create a branch for this issue or link a pull request" que se situa na lateral direita desta issue:

![Screenshot_20230209_165912](https://user-images.githubusercontent.com/18047029/217922925-15aebb84-05a5-4999-9ef8-367cbeda6719.png)

Em seguida, será aberto um popup onde serão fornecidos os comandos para a criação do branch na cópia local do readDiag (a imagem a seguir é apenas um exemplo):

![Screenshot_20230209_170222](https://user-images.githubusercontent.com/18047029/217923163-4d97bf8f-a387-4950-a1b3-c695bcc38481.png)

Em caso de dúvidas sobre como proceder, pode-se usar como referência os seguintes excertos: 

* Abertura de tarefa e criação do branch: https://youtu.be/wZLr6ARrGIU?t=1240
* Pull request das modificações do branch para o master: https://youtu.be/wZLr6ARrGIU?t=2065

## Desenvolvimento do branch

A criação do branch automaticamente fará com que o código do master seja utilizado. Nesse caso, para que o branch atinja o estado das modificações realizadas pelo @edervendrasco, será necessário reintegrar as modificações realizadas à cópia do branch. Isso se faz necessário para que seja possível realizar o pull request posteriormente, i.e., fazer o merge entre a versão do branch e o master.

**Comment by cfbastarz** [comment]
Registro dos commits realizados pelo @edervendrasco sobre esta issue: 87d32fc25b788829818654aeba5792f18109c96a, ac4b68e466375028f29f6313b2005a9d8f0972f5, ca65b43bd55217902ada756bd271333b2467dbb8 e 5cdd39441ce13bec624b86bf2154e08ed638fa91.

**Comment by edervendrasco** [comment]
@cfbastarz, obrigado pelo retorno. 
1) Não me dei conta disso, vou padronizar em inglês (vi agora que a função tocsv também está em português). 
2) Eu havia visto isso mas esqueci de corrigir, obrigado.

**Comment by cfbastarz** [comment]
Foram realizados testes com o branch desta issue em mpaquina local, na Itapemirim/Ilopolis e na Egeon. Para que todos possam testar nas máquina Itapemirim e Egeon, foi preparado o ambiente `readDiag_issue20`. Quando todos tiverem testado o código, faremos a atualização do código do readDiag que está instalado no ambiente padrão `readDiag` nestas máquinas.

## Uso

### Itapemirim/Ilopolis

1. Baixar o código do readDiag - **não é necessário instalar, pois o código já está instalado dentro do ambiente**:
  ```
  git clone git@github.com:GAD-DIMNT-CPTEC/readDiag.git readDiag_issue20
  ```
2. Dentro do diretório do readDiag que foi baixado, alterar para o branch `20-aprimoramento-das-funcoes-de-plotagem-do-readdiag`:
  ```
  cd readDiag_issue20
  git checkout 20-aprimoramento-das-funcoes-de-plotagem-do-readdiag
  ```
3. Acessar o host [http://ilopolis.cptec.inpe.br/](http://ilopolis.cptec.inpe.br/) e navegue até o diretório `readDiag_issue20/doc` e clique no arquivo `gsidiag_tutorial.ipynb`;
4. Na interface do Jupyter, altere o kernel para `readDiag_issue20`. Essa etapa é necessária para que seja possível testar a versão do código.

### Egeon

1. Realizar as etapas 1 e 2 descritas acima;
2. Executar o comando - **anote a porta em que o jupyter está sendo executado, e.g., `jupyter:8889`**:
  ```
  jupyter-notebook --ip='*' --NotebookApp.token='' --NotebookApp.password='' --no-browser
  ```
3. No seu computador, execute o comando a seguir para abrir o Jupyter localmente - onde `localhost:XXXX` deve ser uma porta no seu computador, e.g., `localhost:8820`:
  ```
  ssh -N -f -L  localhost:XXXX:localhost:8889 carlos.bastarz@egeon.cptec.inpe.br
  ```
4. No seu computador, abra o navegador e acesse o endereço `localhost:8820`

**Nota:** caso seja necessário encerrar o Jupyter ou reiniciar o processo, execute os comandos - identifique o processo correspondente ao comando `ssh` executado e encerre-o:
```
ps -ef | grep ssh
kill -9 PID
```

**Comment by sergioh-pessoal** [comment]
Um pequeno comentário
  No item 2  "conda env create -f environmental.yml" parece que o correto seria "conda env create -f environment.yml"

**Comment by cfbastarz** [comment]
Está certo @sergioh-pessoal, obrigado pela correção!
