### ISSUE TITLE
Problema usando dados do AMSU-A em algumas funções de plotagem

### ISSUE THREAD

**Issue by patrick23232** [GAD-DIMNT-CPTEC/readDiag#27]
# Descrição do problema

Algumas funções de plotagem do ReadDIag resultam em erros ao serem utilizados dados de radiância oriundos do AMSU-A com a adequação do tutorial do jupyter notebook. Algumas dessas falhas são correlacionadas por ser uma variação dos parâmetros utilizados nas funções. Dessa forma, o erro não está relacionado a funcionalidade das funções. Assim, presume-se que os erros estejam relacionados com o funcionamento do ReadDiag.

As falhas ocorrem nas seguintes funções:

1. `gd.read_diag.tocsv(   )`
2. `gd.plot_diag.statcount(   )`
3. `gd.plot_diag.ptmap(   )`
4. `gd.plot_diag.time_series(   )`

É apresentado o seguinte padrão de erro:

![image](https://github.com/GAD-DIMNT-CPTEC/readDiag/assets/18521306/a6125885-5681-4417-ac2f-a725c759a8a8)

Na sequência, são apresentadas as configurações iniciais que são divergentes do tutorial; não são descritas as configurações que não foram alteradas uma vez que os problemas não seriam decorrente destas. Em sequência são descritos os erros obtidos de maneira detalhada.

Por fim, é apresentada minha visão sobre a origem do erro. A partir da análise das mensagens, pode-se averiguar qual seria a fonte das mensagens de erro e as falhas de funcionamento das funções do ReadDiag citadas acima.

# Configurações iniciais

É utilizado o tutorial do jupyter notebook com variações para utilização de dados de radiância do AMSU-A. 

A importação das bibliotecas é realizada corretamente, mantendo os comandos originais do tutorial.

Os dados importados são oriundos do satélite NOAA15 em um periodo curto, 2020010100 até 2020010106. São mantidos os parâmetros definidos no tutorial, alterando apenas `dateIni` e `dateFin`. A seguir as linhas de comando utilizadas:

```python
DIRdiag = "/home/patrick/readDiag/data"

varName = "amsua"
varType = "n15"
dateIni="2020010100" 
dateFin="2020010106" 
nHour = "6"          
vminOMA = -2.0       
vmaxOMA = 2.0        
vminSTD = 0.0        
vmaxSTD = 14.0       
Level = 1000
Lay = None           
SingleL = "All" 

datei = datetime.strptime(str(dateIni), "%Y%m%d%H")
datef = datetime.strptime(str(dateFin), "%Y%m%d%H")
dates = [dates.strftime('%Y%m%d%H') for dates in pd.date_range(datei, datef,freq="6H").tolist()]

print(dates)
```

Os arquivos estão contidos no diretório pessoal, dentro da pasta `../readDiag/data`. A geração dos caminhos dos arquivos diagnósticos e a sua leitura estão estruturadas conforme definidos no tutorial.

Ao ser usado o comando a seguir, é obtida a resposta com o nome da variável (`varName`) e o valor de `kx` (ou `varType`):

``` python
gdf_list[tidx].pfileinfo()
```
Resposta:

```
Variable Name : amsua
              └── kx => n15
```

Dessa forma, `kx` é uma string de valor `n15`.

Este valor aparece na estrutura de dados apresentados na descrição do problema ao utilizar o seguinte comando:

```python
gdf_list[tidx].obsInfo[varName]
```

# Mensagens de erro

## Erro 1

Seguindo o tutorial e utilizando a primeira função de plotagem do tutorial, surge o primeiro erro ao usar o comando a seguir:

```python
gd.read_diag.tocsv(gdf_list, varName="amsua", varType="n15", dateIni=dateIni, dateFin=dateFin, nHour="06", Level=1000, Lay = 15, SingleL="OneL")
```
![image](https://github.com/GAD-DIMNT-CPTEC/readDiag/assets/18521306/98425e12-18aa-43f1-899c-5d0d7e421008)

## Erro 2

O segundo erro é semelhante ao primeiro e surge ao ser usado o seguinte comando:

```python
gd.plot_diag.statcount(gdf_list,  varName=varName, varType=varType, noiqc=False, dateIni=dateIni, dateFin=dateFin, nHour=nHour, figTS=True, figMap=True)
```

![image](https://github.com/GAD-DIMNT-CPTEC/readDiag/assets/18521306/ce9c9622-ffe5-4ba1-8760-84d7804a7575)

Erros semelhantes ocorrem nas variações dessa mesma função. Quando variado os parâmetros função `gd.plot_diag.statcount(      )`, são mantidos erros semelhantes. As alterações ocorrem nos parâmetros booleanos: `noiqc`, `figTS` e `figMap`, os comandos completos são os seguintes:

```python
gd.plot_diag.statcount(gdf_list1,  varName=varName, varType=varType, noiqc=True, dateIni=dates[i], dateFin=dates[i], nHour=nHour, figTS=False, figMap=True)
```

```python
gd.plot_diag.statcount(gdf_list,  varName=varName, varType=varType, noiqc=False, dateIni=dateIni, dateFin=dateFin, nHour=nHour, figTS=True, figMap=False)
```

A mensagem de erro é semelhante ao documentado acima, demonstrando que o erro não está nos valores dessas variáveis.

## Erro 3

A terceira mensagem de erro surge ao usar a função `gd.plot_diag.ptmap(     )`. Os comandos no tutorial estão na seguinte forma:

```python
varTypes = ['n15']
idschar="_".join([str(item) for item in varTypes])
gd.plot_diag.ptmap(gdf_list[tidx],varName=varName,varType=varTypes)
figname=varName+"_"+idschar+"_"+"ptmap.png"
plt.tight_layout()
plt.savefig(figname)
```

![image](https://github.com/GAD-DIMNT-CPTEC/readDiag/assets/18521306/2cac0842-6c89-4644-9742-218b8f22e051)

É plotado um mapa "vazio", ou seja, sem os dados:

![image](https://github.com/GAD-DIMNT-CPTEC/readDiag/assets/18521306/34e20bcb-ffec-4916-b4d8-3c34aa96a28f)

## Erro 4

Dando início as figuras utilizando a função `time_series`, surgem novos erros, sendo similares aos primeiros. A partir do comando a seguir, é apresentada a mensagem de erro correspondente:

```python
print("varName= ", varName)
print("varType= ", varType)
print("dateIni= ", dateIni)
print("dateFin= ", dateFin)
print("nHour= ", nHour)
print("vminOMA= ", vminOMA)
print("vmaxOMA= ", vmaxOMA)
print("vminSTD= ", vminSTD)
print("vmaxSTD= ", vmaxSTD)
gd.plot_diag.time_series(gdf_list,varName=varName, varType=varType, dateIni=dateIni, dateFin=dateFin, nHour=nHour, vminOMA=vminOMA, vmaxOMA=vmaxOMA, vminSTD=vminSTD, vmaxSTD=vmaxSTD, Level=Level, Lay=Lay, SingleL=SingleL,Clean=False)
plt.show()
```

![image](https://github.com/GAD-DIMNT-CPTEC/readDiag/assets/18521306/92ec5e60-a77c-49d9-bed6-411eb1c6dcab)

## Erro 5

O quinto erro surge dos comandos:

```python
SingleL = "OneL"
Lay = 15
gd.plot_diag.time_series(gdf_list,varName=varName, varType=varType, dateIni=dateIni, dateFin=dateFin, nHour=nHour, vminOMA=vminOMA, vmaxOMA=vmaxOMA, vminSTD=vminSTD, vmaxSTD=vmaxSTD, Level=Level, Lay=Lay, SingleL=SingleL,Clean=False)
plt.show()
```

![image](https://github.com/GAD-DIMNT-CPTEC/readDiag/assets/18521306/0f90b30c-2d0d-4b9e-8636-c927dac2dd0f)

## Erro 6

O sexto erro é apresentado após ser verificado o `zlevs` dentre os arquivos diagnósticos contendo corretamente os níveis já apresentados em tutorial:

```python
Level = "Zlevs"
Lay = 15
gd.plot_diag.time_series(gdf_list,varName=varName, varType=varType, dateIni=dateIni, dateFin=dateFin, nHour=nHour, vminOMA=vminOMA, vmaxOMA=vmaxOMA, vminSTD=vminSTD, vmaxSTD=vmaxSTD, Level=Level, Lay=Lay, SingleL=SingleL,Clean=False)
plt.show()
```

![image](https://github.com/GAD-DIMNT-CPTEC/readDiag/assets/18521306/2fc80044-9d0c-48d7-8b91-d38655eb32fc)

## Erro 7

Assim como o sexto erro, não é plotado o `time_series` para os comandos a seguir:

```python
Level = "Zlevs"
Lay = None
gd.plot_diag.time_series(gdf_list,varName=varName, varType=varType, dateIni=dateIni, dateFin=dateFin, nHour=nHour, vminOMA=vminOMA, vmaxOMA=vmaxOMA, vminSTD=vminSTD, vmaxSTD=vmaxSTD, Level=Level, Lay=Lay, SingleL=SingleL,Clean=False)
plt.show()
```

![image](https://github.com/GAD-DIMNT-CPTEC/readDiag/assets/18521306/449ab696-cf10-4800-a876-cf9a231c16da)

## Erro 8

Por fim, o último erro apresenta a mensagem similar aos anteriores (4, 5, 6 e 7), uma vez que os comandos e as funções são as mesmas:

```python
Level = None
gd.plot_diag.time_series(gdf_list,varName=varName, varType=varType, dateIni=dateIni, dateFin=dateFin, nHour=nHour, vminOMA=vminOMA, vmaxOMA=vmaxOMA, vminSTD=vminSTD, vmaxSTD=vmaxSTD, Level=Level, Lay=Lay, SingleL=SingleL,Clean=False)
plt.show()
```

![image](https://github.com/GAD-DIMNT-CPTEC/readDiag/assets/18521306/ec3a4ea8-2a61-4144-9540-9dac8eb572dc)

# Análises e conclusões

Ao analisar as mensagens de erro, observa-se um padrão em quase totalidade das funções em que ocorre falha em comum.

![image](https://github.com/GAD-DIMNT-CPTEC/readDiag/assets/18521306/f13a26df-83b1-4197-bff8-80ea40368950)

Observa-se que a origem do erro se encontra no script `datasources.py` encontrada no  diretório `gsidiag/datasources.py`.

O problema se encontra na linha 63:

https://github.com/GAD-DIMNT-CPTEC/readDiag/blob/28c756ba34332986d209e276afd0f58c4683df4c/gsidiag/datasources.py#L63

A solução encontrada para resolver o problema foi comentar a linha, porém não foi avaliado a influência da retirada desta linha de comando para o funcionamento do ReadDiag.

Dessa forma, esse falha teria sido corrigido, apresentando novas falhas a serem apresentada em uma nova issue.

**Comment by patrick23232** [comment]
Uma outra possível solução é substituir o comando `rows.remove([''])` pelos seguintes comandos:

```python
if [''] in rows:
    rows.remove([''])
```

**Comment by cfbastarz** [comment]
Mensagem edita corrigindo typos.

**Comment by cfbastarz** [comment]
Issue que pode estar relacionada com este bug #8.

**Comment by joaogerd** [comment]
Isso é o mesmo problema do issue #8, irei reformular esse método.

**Comment by cfbastarz** [comment]
Bom dia a todos! Associei o branch [#issuefix](https://github.com/GAD-DIMNT-CPTEC/readDiag/tree/issuefix_27) com essa issue. @joaogerd, eu testei as suas modificações nos notebooks de exemplo do repositório e tudo está funcionando. @patrick23232, você pode testar as modificações do branch do @joaogerd para o seu caso? Vou passar as intruções sobre como proceder:

```
conda create -n readDiag-issuefix_27 python=3.9.18
conda activate readDiag-issuefix_27
pip install -r requirements.txt
pip install -e .
```

Dessa forma, cria-se um ambiente separado para testar o código do branch, com o readDiag do branch instalado de forma editável (`pip install -e .`), o que permitirá que outras atualizações do branch possam ser utilizadas sem a necessidade de se repetir todo o processo de instalação.

**Comment by cfbastarz** [comment]
Esse problema foi solucionado, podemos encerrar esta issue?

**Comment by sapucci** [comment]
Ola Carlos. De fato essa solução não está totalmente completa e testada. Com a Caroline verificamos que precisamos ajustar as funções para a radiância e criar uma time series especifica para esse tipo de dados e achamos que esse local é bom para isso. Pode voltar esse essue 27 como "in processing" e aproveitamos para implementar essas melhorias.

**Comment by sapucci** [comment]
Estou reabrindo esse essui, uma vez que me foi permitido. Esse comentário é para justificar essa reabertura.

**Comment by sapucci** [comment]
Foram varios testes com essa solução apresentada pelo joão gerd na #28 com a substituição de uma tabela table por uma estrutura de dados denominada table.yml, mas elas apresentaram problemas e diversas funcionalidades como as times series não estavam mais funcionando, isso para os dados convencionais. Apenas as de plotagem simples funcionavam, imagino que apenas essas foram testadas. Para resolver isso, Caroline sugeriu e testou retirar todos os aspas  dos kx dos dados com apenas numeros como os convencioanais e isso resolveu o problema. A versão no repositorio estava com os aspas em todos os kx mesmo os convencionais e isso não funcionava. Para os kx que precisam de colocar letras esse precisam ter as aspas mantidas como sugerido acima. Observe que para esses casos as funções plo.diag.plot que prota penas um tipo funciona. A função time series para a radiância, não deve funcionar, como assinalado acima, pois não tem o zlev asociado aos dados de radiância, e as camadas é calculadas em função desse valor, por isso os erros destacados acima ao serem usadas. Uma função especifica para a radiância vai ser criada usando os ncha e não o zlev. Veja isso na #38.

**Comment by sapucci** [comment]
Ainda acho que ao inves de trocar o table por table.yml teriamos que ter trocados os satélites no kx da radiância por outros números kx. De toda forma com os comentários acima, essa essue pode ser fechada, pois outras dão andamento a ela e podem tratar de erros aqui não corrigidos, se for o caso.
