### ISSUE TITLE
Erros no script __main__.py ao usar dados do AMSU-A

### ISSUE THREAD

**Issue by patrick23232** [GAD-DIMNT-CPTEC/readDiag#28]
# Descrição do problema

Ao utilizar os dados do AMSU-A, são obtidas mensagens de erro relacionadas ao script `gsidiag/__main__.py`. Esses erros ocorrem em comandos de plotagem dos dados. A seguir serão apresentados os comandos e os erros associados, ao final será disponibilizado uma lista das linhas do script `__main__.py` contendo estas falhas. 

# Configurações iniciais

É utilizado o tutorial do jupyter notebook com variações para utilização de dados de radiância do AMSU-A.

A importação das bibliotecas é realizada corretamente, mantendo os comandos originais do tutorial.

Os dados importados são oriundos do satélite NOAA15 em um periodo curto, 2020010100 até 2020010106. São mantidos os parâmetros definidos no tutorial, alterando apenas `dateIni` e `dateFin`. Os arquivos estão contidos no diretório pessoal, dentro da pasta `../readDiag/data`. A geração dos caminhos dos arquivos diagnósticos e a sua leitura estão estruturadas conforme definidos no tutorial.

# Mensagens de erro

## Erro 1

```python
gd.read_diag.tocsv(gdf_list, varName="amsua", varType="n15", dateIni=dateIni, dateFin=dateFin, nHour="06", Level=None, Lay = 0, SingleL="None")
```

A mensagem é longa pois apresenta um print dizendo que o `kx` utilizado é invalido e sugere outros valores para `kx`

![image](https://github.com/GAD-DIMNT-CPTEC/readDiag/assets/18521306/40148d17-5791-450a-8a84-b32c4461c8c2)

![image](https://github.com/GAD-DIMNT-CPTEC/readDiag/assets/18521306/0762e842-3107-4b99-977b-36cdacf4a844)

## Erro 2

```python
i=0
print(dates[i])
gd.plot_diag.statcount(gdf_list,  varName=varName, varType=varType, noiqc=False, dateIni=dateIni, dateFin=dateFin, nHour=nHour, figTS=True, figMap=True)
```

![image](https://github.com/GAD-DIMNT-CPTEC/readDiag/assets/18521306/0dbf91e0-f093-4f60-a337-251644a1449b)

São obtidos inúmeros erros associados.

# Análise e conclusão

Uma vez que a variável `varType` encontrada nos arquivos do AMSU-A não é uma string mesmo tendo valor `n15`, o script `__main__.py` apresenta erros ao tentar usar esse valor na contrução de títulos de gráficos. Dessa forma, toda vez que um gráfico é plotado, são obtidos erros semelhantes. Isso impede a funcionalidade do ReadDiag com dados do AMSU-A, uma vez que o `varType` `n15` deveria ser uma string, porém isso não ocorre e então não consegue ser concatenada na construção do título do gráfico.

Assim, ao atribuir um valor para a variável `instrument_title` utulizando `str(varType)` ocorre uma erro dizendo que `n15` não tem um tipo específico. Toda vez que é utilizada a variável  `instrument_title` ou o comando `str(varType)`, ocorre a mesma mensagem de erro.

Uma solução adotada foi comentar todas as linhas a seguir, retirando os comandos e dando continuidade a plotagem dos gráficos ou obtenção de novos erros:

https://github.com/GAD-DIMNT-CPTEC/readDiag/blob/28c756ba34332986d209e276afd0f58c4683df4c/gsidiag/__main__.py#L313
https://github.com/GAD-DIMNT-CPTEC/readDiag/blob/28c756ba34332986d209e276afd0f58c4683df4c/gsidiag/__main__.py#L1209
https://github.com/GAD-DIMNT-CPTEC/readDiag/blob/28c756ba34332986d209e276afd0f58c4683df4c/gsidiag/__main__.py#L1240
https://github.com/GAD-DIMNT-CPTEC/readDiag/blob/28c756ba34332986d209e276afd0f58c4683df4c/gsidiag/__main__.py#L1254
https://github.com/GAD-DIMNT-CPTEC/readDiag/blob/28c756ba34332986d209e276afd0f58c4683df4c/gsidiag/__main__.py#L1280
https://github.com/GAD-DIMNT-CPTEC/readDiag/blob/28c756ba34332986d209e276afd0f58c4683df4c/gsidiag/__main__.py#L1295
https://github.com/GAD-DIMNT-CPTEC/readDiag/blob/28c756ba34332986d209e276afd0f58c4683df4c/gsidiag/__main__.py#L1309
https://github.com/GAD-DIMNT-CPTEC/readDiag/blob/28c756ba34332986d209e276afd0f58c4683df4c/gsidiag/__main__.py#L1368
https://github.com/GAD-DIMNT-CPTEC/readDiag/blob/28c756ba34332986d209e276afd0f58c4683df4c/gsidiag/__main__.py#L1374
https://github.com/GAD-DIMNT-CPTEC/readDiag/blob/28c756ba34332986d209e276afd0f58c4683df4c/gsidiag/__main__.py#L1422
https://github.com/GAD-DIMNT-CPTEC/readDiag/blob/28c756ba34332986d209e276afd0f58c4683df4c/gsidiag/__main__.py#L1428
https://github.com/GAD-DIMNT-CPTEC/readDiag/blob/28c756ba34332986d209e276afd0f58c4683df4c/gsidiag/__main__.py#L1466
https://github.com/GAD-DIMNT-CPTEC/readDiag/blob/28c756ba34332986d209e276afd0f58c4683df4c/gsidiag/__main__.py#L1520
https://github.com/GAD-DIMNT-CPTEC/readDiag/blob/28c756ba34332986d209e276afd0f58c4683df4c/gsidiag/__main__.py#L1596
https://github.com/GAD-DIMNT-CPTEC/readDiag/blob/28c756ba34332986d209e276afd0f58c4683df4c/gsidiag/__main__.py#L1641
https://github.com/GAD-DIMNT-CPTEC/readDiag/blob/28c756ba34332986d209e276afd0f58c4683df4c/gsidiag/__main__.py#L1672

**Comment by cfbastarz** [comment]
Mensagem edita corrigindo typos.

**Comment by cfbastarz** [comment]
Issue que pode estar relacionada com este bug #8.

**Comment by cfbastarz** [comment]
Bom dia a todos! Associei o branch [#issuefix](https://github.com/GAD-DIMNT-CPTEC/readDiag/tree/issuefix_27) a esta issue. @patrick23232, você pode testar as modificações que o @joaogerd fez para ver se resolve o seu problema? As instruções para testar estão em https://github.com/GAD-DIMNT-CPTEC/readDiag/issues/27#issuecomment-1910223292.

**Comment by patrick23232** [comment]
Fiz as atualizações para a #27 e obtive um erro similar, porém situada em outra linha. O erro é:

![image](https://github.com/GAD-DIMNT-CPTEC/readDiag/assets/18521306/6b76c31b-88da-4aa1-89a3-e95020f2e3fa)

Adicionei supostas "infos" do AMSU-A do NOAA-15 no arquivo table.yml da seguinte forma:

``python
- kx: "n15"
      details:
         - var: amsua
         abbreviation: SATRAD
         instrument: Satelite NOAA-15
         color: "#1f77b4"
         symbol: "*"
         iuse: "1"
``

O erro se encontra na linha 22, onde "kx" recebe valor inteiro do "table.yml"

**Comment by cfbastarz** [comment]
Esse problema foi solucionado, podemos encerrar esta issue?

**Comment by sapucci** [comment]
ver comentários sobre essa solução na #27 e acompanhe os desdobramentos na #38 com os dados de radiâncias
