### ISSUE TITLE
Estilo 'seaborn-v0_8' não encontrado na biblioteca 'matplotlib'

### ISSUE THREAD

**Issue by patrick23232** [GAD-DIMNT-CPTEC/readDiag#30]
Após correções da issue #27 , é encontrado o seguinte erro em várias funções de plotagem:

![image](https://github.com/GAD-DIMNT-CPTEC/readDiag/assets/18521306/e30ccae6-c814-4315-b3d7-55ab56ada994)

![image](https://github.com/GAD-DIMNT-CPTEC/readDiag/assets/18521306/fdbe40a7-86ec-472c-9f29-72638fa390ce)

As funções em que o erro aparece são: "gd.plot_diag.statcount", "gd.plot_diag.plot", "gd.plot_diag.ptmap", "gd.plot_diag.pcount", "gd.plot_diag.vcount", "gd.plot_diag.kxcount" e "gd.plot_diag.time_series".

É usado arquivos diagnósticos do AMSU-A do NOAA-15, sendo adicionado ao arquivo 'table.yml' as seguinte linhas:

- kx: "n15"
    details:
      - var: amsua
        abbreviation: SATRAD
        instrument: Satelite NOAA-15
        color: "#1f77b4"
        symbol: "*"
        iuse: "1"

É verificado que os pacotes utilizados estão atualizados, assim como o matlibplot. Talvez haja necessidade de utilizar um estilo genérico.

**Comment by cfbastarz** [comment]
@patrick23232, veja a issue #25 onde estas alterações foram descritas. Eu acho que você não está com as versões corretas do seaborn e matplotlib. Veja a [documentação do readDiag](https://gad-dimnt-cptec.github.io/readDiag/pt/instala_local/) e certifique-se que o seu ambiente foi construído exatamente da mesma forma como está na documentação.
