### ISSUE TITLE
Procedure to install readDiag in a Windows 10 OS

### ISSUE THREAD

**Issue by JAAravequia** [GAD-DIMNT-CPTEC/readDiag#36]
The installation on a Windows machine doesn´t work as described in the README.

**Comment by cfbastarz** [comment]
@JAAravequia, to install the readDiag in Windows 10 you will need to install the Windows Subsystem for Linux (WSL) first - take a look at https://learn.microsoft.com/en-us/windows/wsl/install. Then, install the Anaconda Python ditribution for Linux - https://docs.anaconda.com/free/anaconda/install/linux/ inside your WSL, and you will be ready to follow the instructions in the README file (i.e., create an environment with the correct Python version and install readDiag from PyPl or from the master branch). Let me know if you need more help.

**Comment by JAAravequia** [comment]
Obrigado Carlos!

no WSL eu consegui instalar ...

No Windows também instala, porém, no python, importar o gsidiag uma dll não
é encontrada ...

De qualquer forma com o WSL já resolve.


Em qui., 4 de abr. de 2024 às 16:03, Carlos Frederico Bastarz <
***@***.***> escreveu:
