### ISSUE TITLE
Ajustes das funções do readDiag para avaliação da assimilação de dados de radiâncias

### ISSUE THREAD

**Issue by sapucci** [GAD-DIMNT-CPTEC/readDiag#38]
Embora alguns aprimoramentos foram realizados para permitir que o ReadDiag funcione para os dados de radiância na issue #27, ainda muito ajustes precisam ser testados e a solução validada. Ela foi reaberta para a devida validação. E nessa issue aqui serão ajustados o readDiag para funcionar totalmente com os dados de radiância. A função timeseries será recriada com especificidades para a radiância. Uma nova versão será criada mantendo a atual dedicada para os dados convencionais.

Inicialmente pretendia-se fase esse desenvolvimento no branch [#issuefix](https://github.com/GAD-DIMNT-CPTEC/readDiag/tree/issuefix_27), no entanto como a Caroline não tinha permissão para contribuir com o GIT-DAS, e na imposibilidade momentanea de mudar isso, foi feito um clone do trunk e da issue27 para o repositório particular do user Viezelc e essa tarefa deverá ser desenvolvida lá e depois enciada oportunamente para o trunk do Git-DAS. 

Segundo @cfbastarz  que criou, as intruções sobre como proceder para a instalação do branch, com os ajustes para o repositorio do user viezelc, tem-se o seguinte passo-a-passo para os colaboradores:

git clone https://github.com/viezelc/readDiag.git readDiag.Radi
cd readDiag.Radi
git checkout issuefix_27
conda create -n readDiag.Radi python=3.9.18
conda activate readDiag.Radi
pip install -r requirements.txt
pip install -e .

Dessa forma, cria-se um ambiente separado para testar o código do branch, com o readDiag do branch instalado de forma editável (pip install -e .), o que permitirá que outras atualizações do branch possam ser utilizadas sem a necessidade de se repetir todo o processo de instalação.

Instalar o kernel do ambiente readDiag.Radi dentro do Jupyter faca:

python -m ipykernel install --user --name readDiag.Radi --display-name "readDiag-issuefix_27"

Depois disso rode o jupiter-notebook e abra-o pelo brower clicando nos links que são disponibilizados.

**Comment by sapucci** [comment]
PAra essa tarefa foi ciado na __main__.py uma nova função chamada time_serie_radi e nela foi modificado o que seria necessário para os devidos ajustes na função para a mesma funcionar para os dados de radiância. Isso foi feito basicamente modificando a avaraivel de pressão para os numeros dos canais. Uma primeira versão seria selecionao apenas um canal. Ao inves do level a varaivel seria o channel. Ver moficiações na revisão https://github.com/viezelc/readDiag/blob/issuefix_27/gsidiag/__main__.py

**Comment by sapucci** [comment]
Um notebook foi criado nesse desenvolvimento https://github.com/viezelc/readDiag/blob/issuefix_27/notebooks/readDiag_radia_serie_sapu.ipynb
![canal6_amsusNOAA15](https://github.com/GAD-DIMNT-CPTEC/readDiag/assets/105943057/4a75b752-02c0-4bc9-bbb8-d9ce18786cbc)

**Comment by sapucci** [comment]
A Caroline ficou de contribuir gerando um gráfico contendo todos os canais de um sensor explorando um diagrama de hovmoller  como era feito para todos os níveis verticais no caso dos dados convencionais. Uma outra opção é o gráfico a partir de uma lista informada pelo usuário como  argumento de entrada da função.

**Comment by viezelc** [comment]
Testes da função `gd.plot_diag.time_series_radi` utilizando dados do experimento **EXP19**:

```
varName = 'amsua' 
varType = 'n15'   
dateIni = '2024032600' 
dateFin = '2024032618' 
nHour = '6'          
vminOMA = -1.0       
vmaxOMA = 1.0        
vminSTD = 0.0        
vmaxSTD = 1.0       
Level = 1000
Lay = 15           
SingleL = 'OneL' 
```

### 1º Caso: diagrama de hovmoller com **todos os canais** (`channel = None`)

```
varName = 'amsua'
varType = 'n15'
nchan = None
print('varName=',varName,'varType=',varType,'nchan=',nchan,'Lay=',Lay)

gd.plot_diag.time_series_radi(gdf_list,
                         varName=varName, 
                         varType=varType, 
                         dateIni=dateIni, 
                         dateFin=dateFin, 
                         nHour=nHour, 
                         vminOMA=vminOMA, 
                         vmaxOMA=vmaxOMA, 
                         vminSTD=vminSTD, 
                         vmaxSTD=vmaxSTD, 
                         channel=nchan,     
                         Lay=Lay, 
                         SingleL=SingleL,
                         Clean=False)
```

**OmF**
![OmF_all_channels](https://github.com/GAD-DIMNT-CPTEC/readDiag/assets/117780083/ec4cd562-a113-4d66-99c0-5214c3e7d0df)

**OmA**
![OmA_all_channels](https://github.com/GAD-DIMNT-CPTEC/readDiag/assets/117780083/24d396f3-7dd2-4628-9d1e-efd2ac70e95e)

**Comment by viezelc** [comment]
### 2º Caso: diagrama de hovmoller com uma lista de canais indicados (`channel = [7,8,9,10]`)

```
varName = 'amsua'
varType = 'n15'
nchan=[7,8,9,10]
print('varName=',varName,'varType=',varType,'nchan=',nchan,'Lay=',Lay)

gd.plot_diag.time_series_radi(gdf_list,
                         varName=varName, 
                         varType=varType, 
                         dateIni=dateIni, 
                         dateFin=dateFin, 
                         nHour=nHour, 
                         vminOMA=vminOMA, 
                         vmaxOMA=vmaxOMA, 
                         vminSTD=vminSTD, 
                         vmaxSTD=vmaxSTD, 
                         channel=nchan,     
                         Lay=Lay, 
                         SingleL=SingleL,
                         Clean=False)
```

**OmF**
![OmF_list_channels](https://github.com/GAD-DIMNT-CPTEC/readDiag/assets/117780083/6dc47d70-51f3-4a65-867d-62519e93eb70)

**OmA**
![OmA_list_channels](https://github.com/GAD-DIMNT-CPTEC/readDiag/assets/117780083/4254bc8f-5dfa-4f75-992f-95c846bf4bf4)

Observa-se que é preciso modificar/alterar os valores de escala dos diagramas. Retirando os valores de vmin e vmax dos plots de média e STD, a visualização melhora neste caso:

**OmF**
![OmF_list_channels_scale](https://github.com/GAD-DIMNT-CPTEC/readDiag/assets/117780083/1c6be8c8-60f9-4f9c-8626-bb715c95391a)

**OmA**
![OmA_list_channels_scale](https://github.com/GAD-DIMNT-CPTEC/readDiag/assets/117780083/d65263d5-b6da-4188-a904-09edd9a126e0)

**Comment by sapucci** [comment]
Todas essas implementações e melhorias e correções de bugs foram incorporadas na versão https://github.com/viezelc/readDiag/tree/issuefix_27 que será mesclada com a versão trunck do readDiag oportunamente e todas essas aprimoramentos poderão ser utilizados por todos os usuarios. Sendo assim, concluimos essa tarefa com exitos nos objetivos definidos.
