### ISSUE TITLE
Aprimorar a função diag.plot do readDiag adicionando um range selecionado pelo user via argumento na chamada da função

### ISSUE THREAD

**Issue by sapucci** [GAD-DIMNT-CPTEC/readDiag#39]
Ao utilizar a função diag.plot para a radiância é observado que em alguns canais o range automático do python parece não funcionar corretamente pois os pontos plotados ficam em um range onde as cores plotadas são constantes. Veja o problema na figura 9 abaixo.

![canal15](https://github.com/GAD-DIMNT-CPTEC/readDiag/assets/105943057/48789342-5c5d-49a1-95ae-70dcb83e4066)
 
Para aprimorar a função, pretende-se acicionar mais dois argumentos na chamada que seria valores que o user define baseado em sua avaliação previa dos pontos plotados. 

Esse desenvolvimento será realizado no branch [#issuefix](https://github.com/GAD-DIMNT-CPTEC/readDiag/tree/issuefix_27) com a issue27. Segundo @cfbastarz que criou, as intruções sobre como proceder são as que se seguem:

git clone https://github.com/GAD-DIMNT-CPTEC/readDiag.git readDiag-issuefix_27
cd readDiag-issuefix_27
git checkout issuefix_27
conda create -n readDiag-issuefix_27 python=3.9.18
conda activate readDiag-issuefix_27
pip install -r requirements.txt
pip install -e .

**Comment by JAAravequia** [comment]
Devido ao grande número de pontos (spots) de observação de satélites, sugiro ajustar o tamanho da marca plotada, até que as marcas na região equatorial/tropical estejam com uma tamanho pequeno o suficiente para não sobrepor o ponto vizinho.
Para isso, acrescentar o parâmetro markersize nos argumentos da função gd.plot_diag.plot :

 gd.plot_diag.plot(... , markersize=4.8) 

Por exemplo "markersize=4.8" é uma sugestão inicial .

**Comment by sapucci** [comment]
Com as modificações acima feitas pela Caroline, essa tarefa pode ser considerado concluida. Em resumo do problema tem o seguinte, para avaliar o que assimilado da radiância não basta colocar a mascara para o Iuse=1, mas idqc=0, pois no controle de qualidade da radiância o Iuse não é auterado quando a informação não passa no QC, como é feito nos dados convencionais.
