### ISSUE TITLE
Melhorar o aspecto da legenda da função ptmap 

### ISSUE THREAD

**Issue by cfbastarz** [GAD-DIMNT-CPTEC/readDiag#6]
A função `ptmap` apresenta a legenda sobre o gráfico. Nesta issue este detalhe deverá ser consertado de forma que a legenda seja reposicionada para não sobrepor a figura.

Exemplo:

![png](https://gad-dimnt-cptec.github.io/readDiag/imgs/fig06.png)

**Comment by joaogerd** [comment]
corrigido o bug. A legenda deverá aparecer abaixo da figura como no exemplo abaixo:

![image](https://user-images.githubusercontent.com/6088258/183510905-2065e349-de46-48a0-8c2d-87cab9a24315.png)
