### ISSUE TITLE
Incluir barra de cores nas figuras geradas pela função plot

### ISSUE THREAD

**Issue by cfbastarz** [GAD-DIMNT-CPTEC/readDiag#7]
A função plot está plotando figuras sem uma barra de cores. Nesta issue, deverá ser considerada a inclusão de uma barra de cores referente à informação apresentada.

Exemplo:

![png](https://gad-dimnt-cptec.github.io/readDiag/imgs/fig09.png)

**Comment by joaogerd** [comment]
Esta opção está presente na função, porém por padrão está com valor false, para utilizar basta adicionar a opção legend=True durante a plotagem
